### PR TITLE
Remove imports

### PR DESCRIPTION
**Pull request by teto**
I was trying to hack on ihaskell but the build logs were littered with unused imports so I cleaned up a bit.

I fixed the issue with static-canvas. I can drop that commit if you prefer but considering there has been no release since 2019, I think this is an ok fix.

### CODE REVIEW

**Comment by vaibhavsagar** [comment]
Those imports were in there for a reason :smile:. If you want to remove them in a way that maintains backwards compatibility then I am happy to merge.

**Comment by vaibhavsagar** [comment]
No, the CI failed because the imports you removed were required for GHC 8.2.

**Comment by vaibhavsagar** [comment]
I agree that the current `fail-fast` behaviour is unhelpful though, so I've made https://github.com/gibiansky/IHaskell/pull/1302 to change it.

**Comment by teto** [comment]
ah I see the stack 8.2 failure triggered all other jobs to be cancelled ? is there a way to disable that from the .github actions (couldnt find it). Even if I restore some of the imports there are probably others that are safe to remove.

Also what's the policy to drop ghc compatibility ?

**Comment by vaibhavsagar** [comment]
There's no policy for GHC compatibility, but I would prefer to keep support for older GHCs for now.

**Comment by vaibhavsagar** [comment]
Just merged #1302, feel free to rebase for more helpful CI output.

**Review by vaibhavsagar — APPROVED** [review]

**Comment by vaibhavsagar** [comment]
Please rebase to get rid of the `fixup!` commit.

**Comment by teto** [comment]
I've updated the flake so that it can propose different ihaskell versions (instead of just ghc8107).
I've just rebased.

**Comment by vaibhavsagar** [comment]
Thanks!

**Pull request merged**
