### PR TITLE
Fix #350 -- Show diagrams Animations as animated `.gif` images

### LINKED ISSUE #350: Support animations for Diagrams in `ihaskell-diagrams`
Display them as animated gifs!

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/8135859-support-animations-for-diagrams-in-ihaskell-diagrams?utm_campaign=plugin&utm_content=tracker%2F332399&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F332399&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by sumitsahrawat**
I have added a module `IHaskell.Display.Diagrams.Animation` to `ihaskell-diagrams` which is re-exported by `IHaskell.Display.Diagrams`. This fixes #350.

A sample cell:

Sample input cell

Gives output:

Sample output gif

### CODE REVIEW

**Comment by sumitsahrawat** [comment]
@gibiansky I am not sure how to fix the merge conflicts. I have commented on the commit that caused them [here](https://github.com/gibiansky/IHaskell/commit/8337a1db8ebbed621ee3df2d54f23ce1a922807e).

**Comment by sumitsahrawat** [comment]
The output for that same snippet of code, after two new commits looks like this:

Another sample output

**Comment by gibiansky** [comment]
Looks good. In order to deal with merge issues, you should rebase your branch onto master. I just pushed a commit to fix the compilation issue (I think it arose from the 7.10 patch attempt)

**Comment by gibiansky** [comment]
Once it can merge I will go ahead and merge this, it looks good.

**Comment by sumitsahrawat** [comment]
I accidentally made the opposite rebase :(
When I tried to revert it, I found that this PR was automatically closed.

I'll send another one with no merge conflicts.

**Comment by sumitsahrawat** [comment]
And.. it seems like I lost all my code. :(

**Comment by gibiansky** [comment]
Oh no! See [here](http://stackoverflow.com/questions/13154562/have-i-lost-my-changes-after-rebasing) for some details -- maybe it's recoverable? :(

**Comment by sumitsahrawat** [comment]
I'll try and see what I can do.

**Comment by sumitsahrawat** [comment]
I'm used to merging instead of rebasing. Didn't have any idea that they were so different.
I'll see what I can do. It might be easier to just re-write the whole thing.

**Comment by gibiansky** [comment]
It is possible that a merge would have been necessary here, since there were changes to the same files. In general a rebase is preferable as it avoids an extra `merge` commit, which gives you a clean history as well, and makes it seem like the commits all happened synchronously. Sorry for the confusion :(

**Comment by sumitsahrawat** [comment]
The rewrite is complete. Hopefully, it won't be different from the previous one.

Also, the mistake was on my part. I had a misconception that git-rebase was just git-merge without any extra commits. Seems like it was too different from what I had in mind.

The data was still not lost. It was lost when I used `--set-upstream` on the `diagrams-animation` branch, which was not rebasing due to absence of an upstream. I might've been able to recover had the data not been lost there.

It's working again, and that's what matters. Thanks for the explanation. :+1:

**Pull request closed without merging**
