### PR TITLE
Remove conversion of svg to html for generic usage.

### PR DESCRIPTION
**Pull request by GregorySchwartz**
On my setup it works with both browser and emacs front-ends.

### CODE REVIEW

**Comment by vaibhavsagar** [comment]
This is great, thanks!

**Comment by GregorySchwartz** [comment]
It seems as though https://github.com/gibiansky/IHaskell/issues/187 was the reason for embedding. If this is the case, I don't think embedding is the answer, rather replacing the glyph like in https://github.com/jupyter/notebook/issues/333. Is it possible to get the cell id per call? If so, we can pass that id to the MimeSvg and just add those ids to all glyphs, clips, images, and gradients as well like they do in IJulia.

**Comment by GregorySchwartz** [comment]
IJulia uses a timestamp as an id. The publish function already is in the IO monad, so that would be a simple solution. I can try to add it in. Should this merge be reverted in the meantime?

**Comment by vaibhavsagar** [comment]
Sure, I've reverted it for now.

**Pull request merged**
