### PR TITLE
Drop support for GHC < 8.0

### PR DESCRIPTION
**Pull request by erikd**

### CODE REVIEW

**Comment by erikd** [comment]
Don't merge this yet. Some more stuff to be cleaned out.

**Comment by vaibhavsagar** [comment]
Thanks so much! Can you also remove the `binPkgDb` flag from `ihaskell.cabal` as well? That only exists to support GHC 7.10. Otherwise you can merge your changes as they are and I can do that.

**Comment by erikd** [comment]
@vaibhavsagar Please feel free to merged this. Next task for me is `-Wall`.

**Comment by vaibhavsagar** [comment]
Thanks so much!

**Pull request merged**
