### PR TITLE
Switch back to parseUrl

### PR DESCRIPTION
**Pull request by erikd**

### CODE REVIEW

**Comment by erikd** [comment]
This build failure had nothing to do with my change.

**Comment by leftaroundabout** [comment]
[`parseUrlThrow`](http://hackage.haskell.org/package/http-client-0.5.6.1/docs/Network-HTTP-Client-Internal.html#v:parseUrlThrow) is fine, but it only works with `http-client>=0.4.30`. I adress this is in b52d484fd112048cf101f34af930d5017c825684

**Comment by erikd** [comment]
@leftaroundabout Yes, that fixes it when building with cabal, but not when building with stack and the current stack resolver.

**Comment by vaibhavsagar** [comment]
Is this still an issue?

**Comment by erikd** [comment]
It was never an issue for me because I don't use stack.

**Comment by vaibhavsagar** [comment]
Okay, closing.

**Pull request closed without merging**
