### PR TITLE
Make unique labels using a timestamp for svg elements.

### PR DESCRIPTION
**Pull request by GregorySchwartz**
Addresses https://github.com/gibiansky/IHaskell/issues/877 and issues raised in https://github.com/gibiansky/IHaskell/pull/1009.

### CODE REVIEW

**Comment by vaibhavsagar** [comment]
Can you rebase on top of current `master` please? Also, did you consider using something like [`Data.Unique`](http://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Unique.html) instead of the timestamp?

**Comment by GregorySchwartz** [comment]
While `Data.Unique` is a good idea, it would not be preserved between sessions, so it would become non-unique if saving and reopening. The best idea would be to use the cell number, but I don't know how to get that. So if it's cell `[34]` then the results of that cell would always be `34` for the label.

**Comment by GregorySchwartz** [comment]
Rebased.

**Comment by GregorySchwartz** [comment]
Looks like the check failed because of `stack-8.0`. I'm changing `getSystemTime` to `getCurrentTime` and using the date + picoseconds versus seconds from unix epoch as a workaround.

**Comment by GregorySchwartz** [comment]
Used earlier version of time for `stack-8.0`. The `id` label, using date and picoseconds, contains "-" and "." characters, but it seems to meet specs so I left it as is.

**Comment by vaibhavsagar** [comment]
Thanks!

**Pull request merged**
