### PR TITLE
Add IHaskell.Display.IHaskellDisplay instance for DecsQ

### PR DESCRIPTION
**Pull request by cje**

### CODE REVIEW

**Comment by gibiansky** [comment]
I'm getting the error
```
Template Haskell error: Can't do `reify' in the IO monad
```
in the console and the error
```
user error (Template Haskell error)
```
in the notebook. 

What's going on?

**Comment by gibiansky** [comment]
The issue is with `TH.runQ decl` – that is the line that throws the error. How should this be fixed?

**Comment by gibiansky** [comment]
It looks like this is a well known error... Is there any way around this?  Perhaps writing Haskell code to a file, then using something like `zeroth`, then reading from that file? (That approach used to be used with `hlint` until the new API came about.)

**Comment by cje** [comment]
That's odd - that fix worked fine for me testing.  What's the expression
you're evaluating?  I'll have a look shortly.

**Comment by gibiansky** [comment]
Anything which calls `reify`, I think. I used `makeLenses ''Foo`. (Simpler things, like `[| \x -> x + x |]`, work, I believe.)

**Comment by gibiansky** [comment]
Actually, not with the example given above, since that's `ExpQ`. `ExpQ` could also have an instance that is very similar, right?

What example did you use for testing?

**Pull request merged**
