### PR TITLE
correct a typo for the singletons version in ihaskell-widgets.cabal

### PR DESCRIPTION
**Pull request by artuuge**
issue #589

### CODE REVIEW

**Comment by sumitsahrawat** [comment]
@artuuge Can you squash those commits into one, as the first two are just reverted by the third and fourth.

**Comment by artuuge** [comment]
Ok, it is now squashed. The last commit has travelled backwards in time a little and the first four have annihilated each other.

**Comment by sumitsahrawat** [comment]
Your master branch has diverged from the IHaskell master branch. I was writing the mini-tutorial below, when you commented:

---

@artuuge I also faced some issues with rebasing when I started working on IHaskell. Try and see how this goes:

```bash
# The upstream repository
git clone https://github.com/gibiansky/IHaskell.git
cd IHaskell

# Add your fork as a remote
git remote add fork https://github.com/artuuge/IHaskell.git

# Replace your fork with the upstream repo
git push -u fork master --force
```

Now, your fork stands equal to the upstream repository. Then, we make some changes in a new branch. It is not recommended that you work on the master branch, as your branch might diverge from the upstream branch just like the current situation:

```bash
# git checkout -b <new-branch-name>
git checkout -b singletons-upper-bound # Any suitable branch name

# Now you make your changes
# ....

# Push them to your fork, creating a new branch online
git push -u fork singletons-upper-bound
```

Then send a PR merging the newly created branch to the upstream master branch.

---

**Comment by artuuge** [comment]
Ok, I am going to follow these instructions. They look better than what I have done: 'git rebase -i HEAD~6', change picks to squashes, and then rewrite history with 'git push origin master --force'.

**Comment by sumitsahrawat** [comment]
That works very well when you have a separate branch.

I can't determine what exactly went wrong here, but most probably you made some changes to your own master branch, while the upstream master branch progressed in a different direction. This should not cause any problems in itself.

**Comment by artuuge** [comment]
Ok, the pull request is submitted. Everything looks compatible. :-) Thanks a lot!

**Comment by sumitsahrawat** [comment]
You're welcome :+1:

**Pull request closed without merging**
