### PR TITLE
Add dependency on chunked-data explicitly

### PR DESCRIPTION
**Pull request by sumitsahrawat**
Constrain the version of chunked-data used by classy-prelude, thus
fixing issue #491 and fixing the build.

The issue did not arise directly from `classy-prelude`, as the package version was constrained already.

### CODE REVIEW

**Comment by gibiansky** [comment]
@sumitsahrawat Thanks for the PR. Working on getting a new release on Hackage, 0.6.1. `IHaskell` is already up, also updating `ihaskell-rlangqq` and `ihaskell-diagrams` now. I think those are the only two display packages that need updating (i should keep better track of this)

**Comment by gibiansky** [comment]
@sumitsahrawat Ugh, nevermind. More dependency issues, clashes with `classy-prelude`, etc. Should upload new versions of everything shortly...

**Comment by gibiansky** [comment]
I have to leave now so I'll get this done this evening (in 12-16 hours). Apologies for delay.

**Comment by sumitsahrawat** [comment]
Great :+1:. We might finally get some activity on https://github.com/jupyter/docker-demo-images/pull/29.

**Comment by gibiansky** [comment]
Uploaded 0.6.2 and so on to Hackage.

**Comment by sumitsahrawat** [comment]
I changed the `Dockerfile` to use `ihaskell-0.6.2.0` from hackage, and it has been merged. Just a matter of time before it's online now.

**Pull request merged**
