### PR TITLE
Enable CodeMirror syntax highlighting in JupyterLab

### LINKED ISSUE #1199: Enable syntax highlighting in JupyterLab by default
I think Haskell syntax highlighting should be enabled by default. One way to do that would be to insert a switch in `kernel.json`, maybe like

```Haskell
++ ["--codemirror", "Haskell"]
```

after the `--ghclib` argument.

https://github.com/gibiansky/IHaskell/blob/ef698157f44960566687a308e3455b5ba031eb43/src/IHaskell/IPython.hs#L140-L144

But if we did this, then how would syntax highlighting be disabled?

Maybe there's a more natural way to accomplish this.

Reference: https://github.com/gibiansky/IHaskell/pull/1191

### PR DESCRIPTION
**Pull request by jamesdbrock**
Continuation of https://github.com/gibiansky/IHaskell/pull/1191

Resolves #1199

Also will satisfy older issues #1202 #1120

### CODE REVIEW

**Comment by vaibhavsagar** [comment]
We actually define a specific `ihaskell` mode [here]()https://github.com/gibiansky/IHaskell/blob/66333eaf25601d55cfd27760b5bd22866a7526f1/html/kernel.js#L30, so I'm not on board with changing the default. Adding a `--codemirror` sounds good though.

**Comment by vaibhavsagar** [comment]
Is there a way to change the default for JupyterLab only without affecting classic notebooks?

**Comment by vaibhavsagar** [comment]
Alternatively, maybe it is time to change the default and rip out our custom Codemirror mode definition? I'm not sure, I would need to think about it some more. I think making it configurable is a good idea and have no objections there, but I don't want to change the default just yet.

**Comment by jamesdbrock** [comment]
Oh okay, I see what that special CodeMirror "ihaskell" mode is about, yeah this commit probably will not behave correctly.

The CodeMirror built-in mode is name "haskell".

We have a special `multiplexingMode` named "ihaskell" which detects if a code cell is Haskell and should use the "haskell" mode, or if the code cell is a `:` command and should use the "text/plain" mode.

**Comment by jamesdbrock** [comment]
I have some observations to make about the current behavior of `ihaskell` Codemirror on the master branch:

1. `--codemirror haskell` will enable syntax highlighting in Lab.
2. `--codemirror Haskell` will enable syntax highlighting in Lab.
3. `--codemirror ihaskell` will not enable syntax highlighting in Lab.
4. In the classic Notebook no switch is needed, Codemirror is already enabled.

**Pull request closed without merging**
