### PR TITLE
Update for #476, use CPP to manage different versions

### PR DESCRIPTION
**Pull request by sumitsahrawat**
There might be better approaches. Fiddling around with `ghc-parser.cabal` didn't help, so I chose this.

### CODE REVIEW

**Comment by gibiansky** [comment]
Hmm... This should not be necessary. In https://github.com/gibiansky/IHaskell/issues/476 the poster is trying with GHC 7.10, which *hypothetically* does *not* require a Happy parser build at all, as the GHC 7.10 parser api exposes enough for us to work with. 

The issue is this line:

```
        hs-source-dirs:    generic-src src-7.10
```
There is no auto-generated `src-7.10` directory  (and there shouldn't be; it's not autogenerated). However, it *does* exist in the repo.

I think the required change to #476 is actually adding `src-7.10/Language/Haskell/GHC/HappyParser.hs` to the `extra-source-files` list.

**Comment by gibiansky** [comment]
Implementing the attempt here: https://github.com/gibiansky/IHaskell/pull/480

Closing for now; if #480 doesn't work will re-open and look into CPP. Hopefully can avoid that. Either way thanks for looking into this and kicking this off.

**Comment by sumitsahrawat** [comment]
I experimented with the cabal file, and I noticed something interesting. Reordering the clauses in the if-else chain has visible effects on the contents of the sdist tarball.

For example:

The default order includes `src-7.6` and excludes everything else.

Reordering as follows:

```
  if   impl(ghc >= 7.8) && impl(ghc < 7.8.3)
    hs-source-dirs:      generic-src src-7.8.2
  else
    if impl(ghc >= 7.6) && impl(ghc < 7.8)
      hs-source-dirs:    generic-src src-7.6
    else
      if impl(ghc < 7.10)
        hs-source-dirs:    generic-src src-7.8.3
      else
        hs-source-dirs:    generic-src src-7.10
```

Creates a tarball with 7.8.2 included.

---

Adding `src-7.10/Language/Haskell/GHC/HappyParser.hs` to `extra-source-files` adds that file to the tarball, but there are still files missing from it.

**Comment by gibiansky** [comment]
I went through the same process as well, and was confused as to why it was happening.

Which files are missing from it?

(If you are referring to the `src-7.8.*` directories, then actually that's ok, because the `src-7.6` and `src-7.8` directories shouldn't be in the tarball in the first place. They are generated by `build-parser.sh`, which is called from `Setup.hs` upon installation. So `src-7.6` actually *shouldn't* be in the tarball (and I didn't know until today that it was even being included). *Only* `src-7.10` actually needs to be in the tarball; the other ones are generated from the `.pp` `HappyParser` files.)

**Pull request closed without merging**
