### PR TITLE
minimal change to get IHaskell kernel.js loaded at the right time

### PR DESCRIPTION
**Pull request by Carreau**
Not indented, I'll strip that down, but you should not need the first on notebook loaded I guess.

### CODE REVIEW

**Comment by gibiansky** [comment]
Thanks! This doesn't seem to change whether or not `app_initialized.NotebookApp` is called though. I also tried `notebook_loaded.Notebook`, but that doesn't seem to be called either...

**Comment by gibiansky** [comment]
Do you know of any examples of kernel.js from other kernels? I looked around but could not find any

**Comment by gibiansky** [comment]
Oh, I understand. Got it.

**Comment by Carreau** [comment]
Yeah, I'm writing the docs for it right now.

**Comment by Carreau** [comment]
Ok, strugling with git book, but seem to be online now : http://carreau.gitbooks.io/jupyter-book/content/kerneljs.html  does that make sens ?

**Comment by gibiansky** [comment]
Got it, thanks. Makes sense!

**Pull request merged**
