### PR TITLE
Passthru of some release internal expressions

### PR DESCRIPTION
**Pull request by jraygauthier**
This is so that these can be reused (e.g.: for
specifying a nixos jupyter service kernel).

Helps with https://github.com/gibiansky/IHaskell/issues/920.

Allows me reuse the release from nixos in the following way:

```nix
    nixpkgs.config.packageOverrides = super: let self = super.pkgs; in rec
    {
      ihaskellNixpkgsCfg = {
        # allowBroken = true;

        packageOverrides = super: let self = super.pkgs; in
          let
              # See pkgs/development/haskell-modules/lib.nix for available helpers.
              overrideCabal = super.haskell.lib.overrideCabal;
              unmarkBroken = drv: super.haskell.lib.overrideCabal drv (drv: { broken = false; });
              doJailbreak = super.haskell.lib.doJailbreak;
              overrideSrc = super.haskell.lib.overrideSrc;
              addSetupDepend = super.haskell.lib.addSetupDepend;
          in rec
        {
          haskell = super.haskell // {
            packageOverrides = self: super: rec {

              static-canvas = doJailbreak (unmarkBroken super.static-canvas);

              Chart = self.callHackageDirect {
                pkg = "Chart";
                ver = "1.9.1";
                sha256 = "0aiq9r78yhma1xzhwl2xlzwqb2c59k6a4jjvdpninwm6lngac3s7";
              } {};
              Chart-cairo = self.callHackageDirect {
                pkg = "Chart-cairo";
                ver = "1.9.1";
                sha256 = "0ambbkxbndjqxr0c4pysn87b3z0f8zpgvldj4qjbyazadna9k807";
              } {};
            };
          };
        };
      };
      # ihaskellNixpkgs = pkgs;

      ihaskellNixpkgsSrc = builtins.fetchTarball {
        url = "https://github.com/NixOS/nixpkgs-channels/archive/2df17ecf1b748379a349f763f376bad173bff83b.tar.gz";
        sha256 = "10s6p0i3g4jkmdgfh3zb73baapks6gwcfl2p9hc3j490ly2wa0kv";
      };
      ihaskellNixpkgs = import "${ihaskellNixpkgsSrc}" { config = ihaskellNixpkgsCfg; };

      ihaskellRepoRemote = builtins.fetchTarball {
        url = "https://github.com/jraygauthier/IHaskell/archive/9dd3ed664c24589a2ef2c1599affb48592b91b38.tar.gz";
        sha256 = "13sja043kpag8h4whqf4nhcl6pzr3ikyaz32zq8iadfb27rf1jch";
      };

      ihaskellRepo = ihaskellRepoRemote;

      ihaskellSystemPackages = pkgs: [
      ];

      ihaskellPackages = hps: with hps; [
        ihaskell-blaze
        ihaskell-diagrams
        ihaskell-charts
      ];

      ihaskellRelease86 = (import "${ihaskellRepo}/release-8.6.nix" {
        nixpkgs = ihaskellNixpkgs;
        packages = ihaskellPackages;
        systemPackages = ihaskellSystemPackages;
      });
  };

  services.jupyter.enable = true;
  # Default pw: test.
  services.jupyter.password = "'sha1:1b961dc713fb:88483270a63e57d18d43cf337e629539de1436ba'";
  services.jupyter.kernels = {
    python3 = let
      env = (pkgs.python3.withPackages (pythonPackages: with pythonPackages; [
        ipykernel
        pandas
        scikitlearn
      ]));
    in {
      displayName = "Python 3 for machine learning";
      argv = [
        "${env.interpreter}"
        "-m"
        "ipykernel_launcher"
        "-f"
        "{connection_file}"
      ];
      language = "python";
      logo32 = env + "/${env.sitePackages}/ipykernel/resources/logo-32x32.png";
      logo64 = env + "/${env.sitePackages}/ipykernel/resources/logo-64x64.png";
    };

    haskell = let
      ihaskellEnv = pkgs.ihaskellRelease86.ihaskellEnv;
      ihaskellWrapperSh = pkgs.ihaskellRelease86.ihaskellWrapperSh;

    in {
      displayName = "Haskell for machine learning";
      argv = [
        "${ihaskellWrapperSh}/bin/ihaskell-wrapper"
        "kernel"
        "--ghclib"
        "${ihaskellEnv}/lib/ghc-${ihaskellEnv.version}"
        # "--debug"
        "+RTS"
        "-M3g"
        "-N2"
        "-RTS"
        "{connection_file}"

      ];
      jsFile = pkgs.ihaskellRelease86.ihaskellJsFile;
      logo64 = pkgs.ihaskellRelease86.ihaskellLogo64;
      language = "haskell";
    };
  };
```

### CODE REVIEW

**Comment by vaibhavsagar** [comment]
Thanks for this PR! I tried building it and running `result/bin/ihaskell-notebook`:

```
[vaibhavsagar@nixos:~/repos/IHaskell]$ result/bin/ihaskell-notebook 
Unknown flag: -N
Error executing Jupyter command 'notebook': [Errno 2] No such file or directory
```

Please fix this.

**Comment by jraygauthier** [comment]
Done. Thanks for the quick review.

**Comment by vaibhavsagar** [comment]
This still doesn't work for me:

```bash
[vaibhavsagar@nixos:~/repos/IHaskell]$ nix-build release-8.6.nix 
/nix/store/8vjpq6c7c46lsh9g4yb68hs2la67174a-ihaskell-with-packages

[vaibhavsagar@nixos:~/repos/IHaskell]$ result/bin/ihaskell-notebook 
Error executing Jupyter command 'notebook': [Errno 2] No such file or directory
```

I won't merge this unless I can run `result/bin/ihaskell-notebook` exactly as before.

**Comment by jraygauthier** [comment]
That's strange, I do not get this error running the same instructions:

```bash
$ nix-build -I nixpkgs=../nixpkgs_root release-8.6.nix && ./result/bin/ihaskell-notebook
/nix/store/zwmm3b5w633jjr731dkzrzkhfl5685am-ihaskell-with-packages
[I 21:20:56.830 NotebookApp] The port 8888 is already in use, trying another port.
[I 21:20:56.868 NotebookApp] JupyterLab extension loaded from /nix/store/3wmdk3ywc8pwk8f90xgvccyjcc20zvbm-python3-3.7.3-env/lib/python3.7/site-packages/jupyterlab
[I 21:20:56.868 NotebookApp] JupyterLab application directory is /nix/store/j6rbl501ybsa4m6gwvd82sa753vapip4-python3.7-jupyterlab-0.35.4/share/jupyter/lab
[I 21:20:56.870 NotebookApp] Serving notebooks from local directory: /home/rgauthier/dev/IHaskell
[I 21:20:56.870 NotebookApp] The Jupyter Notebook is running at:
[I 21:20:56.870 NotebookApp] http://localhost:8889/?token=9917521053eb2b640e43bd7e597e2643764297e41618667b
[I 21:20:56.870 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 21:20:56.895 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///run/user/1000/jupyter/nbserver-16342-open.html
    Or copy and paste one of these URLs:
        http://localhost:8889/?token=9917521053eb2b640e43bd7e597e2643764297e41618667b
```

**Comment by jraygauthier** [comment]
Sorry for all these errors, I now got it to run properly:

```bash
$ nix-build -I nixpkgs=../nixpkgs_root release-8.6.nix && nix-shell -p which -p firefox  --pure --run './result/bin/ihaskell-notebook'
/nix/store/npsm7xhdpf4bx9hpi3pdl5ldxka70rqr-ihaskell-with-packages
[I 21:41:50.625 NotebookApp] The port 8888 is already in use, trying another port.
[I 21:41:50.676 NotebookApp] JupyterLab extension loaded from /nix/store/3wmdk3ywc8pwk8f90xgvccyjcc20zvbm-python3-3.7.3-env/lib/python3.7/site-packages/jupyterlab
[I 21:41:50.676 NotebookApp] JupyterLab application directory is /nix/store/j6rbl501ybsa4m6gwvd82sa753vapip4-python3.7-jupyterlab-0.35.4/share/jupyter/lab
[I 21:41:50.678 NotebookApp] Serving notebooks from local directory: /home/rgauthier/dev/IHaskell
[I 21:41:50.678 NotebookApp] The Jupyter Notebook is running at:
[I 21:41:50.678 NotebookApp] http://localhost:8889/?token=1b010022c8eff26bca0b0fbe9fd58c720c4d02baf2cd3d33
[I 21:41:50.678 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 21:41:50.693 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///home/rgauthier/.local/share/jupyter/runtime/nbserver-11088-open.html
    Or copy and paste one of these URLs:
        http://localhost:8889/?token=1b010022c8eff26bca0b0fbe9fd58c720c4d02baf2cd3d33
```

**Comment by vaibhavsagar** [comment]
No need to apologise! Thank you for getting this working :smile:.

**Pull request merged**
