### PR TITLE
Adding empty case to set

### PR DESCRIPTION
**Pull request by houshuang**
Better than having kernel panic on typing ":set" without a flag... Not sure if this should have a help text or an error text.

### CODE REVIEW

**Comment by gibiansky** [comment]
Good catch. I'm happy with what it currently says there.

**Comment by aavogt** [comment]
ghci interprets that as "what options are set":
```
> :set
options currently set: none.
base language is: Haskell2010
with the following modifiers:
  -XNoDatatypeContexts
  -XNondecreasingIndentation
GHCi-specific dynamic flag settings:
  -fbreak-on-exception
other dynamic, non-language, flag settings:
  -fimplicit-import-qualified
warning settings:
  -fwarn-monomorphism-restriction
```
I think we should follow ghci's behavior if there's no reason to do things differently

**Comment by gibiansky** [comment]
Hmm, agreed. I will still keep this merged as an error message is better than a crash, but the ghci version is probably the desired behaviour.

**Comment by houshuang** [comment]
@bgamari seems to have already implemented this. https://github.com/bgamari/IHaskell/commit/9abaee86cdb573dcc7ff40cf6169e25b7dd91b2a

**Comment by bgamari** [comment]
@houshuang indeed I have. I've split out this change from the rest of the GHC 7.10 changes and opened pull request #375.

**Pull request merged**
