### PR TITLE
WIP: Remove stack install gtk2hs-buildtools --fast

### PR DESCRIPTION
**Pull request by habemus-papadum**
- [x] Remove from travis
- [ ]  Update docs
- [ ]  Update install scripts 
- [X]  Track down why this was even needed in the first place : introduced here de595bd

### CODE REVIEW

**Comment by vaibhavsagar** [comment]
Can you rebase your changes please :smiley:?

**Comment by habemus-papadum** [comment]
moved to #765

**Comment by vaibhavsagar** [comment]
For next time: you can rebase your changes without opening a new PR.

**Comment by habemus-papadum** [comment]
@vaibhavsagar not if you want to do it from your ipad's web browser 😄

**Pull request closed without merging**
