### PR TITLE
[WIP] GHC 8.0 support

### PR DESCRIPTION
**Pull request by bgamari**
Haven't had a chance to test this yet but I thought I'd open a PR to make sure no one ends up duplicating this work.

### CODE REVIEW

**Comment by utdemir** [comment]
Hi @bgamari ,

IHaskell compiles with this PR only if you relax ghc-parser's upper bound of base.

However, when I run a notebook, I can not interpret anything, everything returns `Prelude.head: empty list`.:

screen shot 2016-08-08 at 23 09 26

There are a few `head` calls on the codebase, but there isn't any clue about which `head` that is, and my Haskell is not enough to investigate it. I tried looking for `head` calls near your changes, but found nothing.

**Comment by bgamari** [comment]
Utku Demir <notifications@github.com> writes:

> Hi @bgamari ,
>
> IHaskell compiles with this PR only if you relax ghc-parser's upper bound of base.
>
Indeed, I started down this path but ultimately ran out of time before
getting anything to work. I'm moving across an ocean this week, but
hopefully in a few weeks I'll again have time to look into this.

Cheers,

- Ben

**Comment by NickSeagull** [comment]
@bgamari I had already started working on this same thing, but I'll dispose all my work in favor of yours. If you don't mind I'll grab your additions and work on them. I'll give you attribution in the commit message.

I'd fork your branch, but I already have some changes that I've added

**Comment by bgamari** [comment]
Nikita Tchayka <notifications@github.com> writes:

> @bgamari I had already started working on this same thing, but I'll dispose all my work in favor of yours. If you don't mind I'll grab your additions and work on them. I'll give you attribution in the commit message.
>
Sure, please do!

As far as I know the only issue is the `Prelude.head` issue described
above. I've spent a bit of time trying to locate the culprit but didn't
get very far. Good luck and let me know if you have any questions.

**Comment by barakber** [comment]
This is the `Prelude.head`:
https://github.com/DataHaskell/IHaskell/blob/master/src/IHaskell/Eval/Evaluate.hs#L1170
Also, there's something wrong with the evaluation of the syntax in these 2 lines:
https://github.com/DataHaskell/IHaskell/blob/master/src/IHaskell/Eval/Evaluate.hs#L1132
https://github.com/DataHaskell/IHaskell/blob/master/src/IHaskell/Eval/Evaluate.hs#L1133
so I can't move pass this point:
https://github.com/DataHaskell/IHaskell/blob/master/src/IHaskell/Eval/Evaluate.hs#L1159
it's crashing there.

**Comment by bgamari** [comment]
I had a bit of time in between builds to plug away at this a bit more. I have pushed a patch which fixes the `head` issue. Unfortunately there are a few issues that remain (e.g. I was able to crash the thing fairly easily, `:info` doesn't quite work, etc.).

**Comment by vaibhavsagar** [comment]
Included in e97b70198fe6b56c81a15430c37e777b4979c61c, thanks for your help with this @bgamari!

**Pull request closed without merging**
