### PR TITLE
Fix #456 -- Update pager for message spec v5

### LINKED ISSUE #456: Pager doesn't work
The pager doesn't seem to work right now, as demonstrated by `:info Integral` or anything of the like. This is probably due to the v5 messaging spec migration.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/10027613-pager-doesn-t-work?utm_campaign=plugin&utm_content=tracker%2F332399&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F332399&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by sumitsahrawat**
It works :sparkles:

screenshot from 2015-04-08 20 23 11

### CODE REVIEW

**Comment by sumitsahrawat** [comment]
@gibiansky Does this look good?

It can be extended further to support more mimetypes, I kept it simple because only string representations were used beforehand.

**Comment by gibiansky** [comment]
Looks good.

Can you add support for full display data bundles? 

This would involve finding `EvaluationResult` in `Types.hs` and editing the `pagerOut` field to be a `[DisplayData]`, and then fixing all the resulting breakages in `Evaluate.hs` (there should only be one or two).

Sorry for my non-responsiveness lately, by the way. The work you're doing looks great and I'll get back to it ASAP – I have a big presentation later today and hopefully will have a bit more time to review the big PR soon.

**Comment by sumitsahrawat** [comment]
It looks good. I will work on the tests later.

How did the presentation go? I am also stuck with academics, so going slow seems to be a good option for both of us. I use the time I get to go trekking in the source and issues, and it's going good.

**Comment by sumitsahrawat** [comment]
@gibiansky It works now. Can you take a look?

**Comment by gibiansky** [comment]
@sumitsahrawat Merged this. Made a small change removing `IsString`; there's no concrete and obvious way to go from `String` to `DisplayData`, and it's not really cleaner and doesn't save code. 

Haven't pushed it to `master` yet, waiting for https://github.com/gibiansky/IHaskell/pull/474 to complete Travis tests. Once Travis confirms, will push to master.

**Pull request closed without merging**
