### PR TITLE
Widgets 4.0 -- Finishing touches

### PR DESCRIPTION
**Pull request by sumitsahrawat**
@gibiansky I assumed that all values being sent for `margin`, `width`, etc (which previously required being sent as strings), are pixel values. This also explains why they had to be sent as strings.

We can also extend them, to provide an API like this:

```haskell
setField w Height (Em 2)
setField w Width (Px 200)
```

The current one is similar in power to what we had earlier, when IPython understood that plain numbers were just `"px"` valules. Do you think that a change is worth the trouble?

I also updated the example notebooks, but the `PlaceProxy` widget didn't work as I expected, so will fix it and then add an example.

### CODE REVIEW

**Comment by sumitsahrawat** [comment]
Trying to use `PlaceProxy` inside IPython also lead to some errors in the console. Searching the example notebooks from the IPywidgets repository shows that there is no mention of either the `Proxy` widget, or the `PlaceProxy` widget. Maybe @jdfreder can comment on that.

I'll go ahead and remove the `PlaceProxy` widget for now.

Also, we seem to be having out of memory issues even without the widgets ([build log](https://travis-ci.org/gibiansky/IHaskell/jobs/80698102#L1692-L1693)).

**Comment by jdfreder** [comment]
I believe either @jasongrout or @sylvaincorlay authored the proxy widget, I haven't had a chance to play with it myself yet.

**Comment by sumitsahrawat** [comment]
The proxy widget works just fine. When using the PlaceProxy widget, the console shows some errors.

**Comment by jasongrout** [comment]
What errors?

**Comment by sumitsahrawat** [comment]
The example below shows the error I recieved:

image

**Comment by sumitsahrawat** [comment]
@jasongrout Is this a valid issue, or am I using it wrong?

**Comment by SylvainCorlay** [comment]
@sumitsahrawat the selector is the css selector of where you want the widget to be displayed. For example,  you may have created a div element in a markdown cell with a unique id and you want a slider to be displayed there in the middle of the rendered markdown.

**Comment by sumitsahrawat** [comment]
Thanks for the info. It was really helpful :+1:.

I can't believe I never thought of CSS selectors. Sorry for bothering you.

**Comment by SylvainCorlay** [comment]
@sumitsahrawat you did not bother me at all. It is great that you are working on the Haskell bindings!

**Comment by sumitsahrawat** [comment]
@gibiansky The build is failing due to https://github.com/amcphail/plot/issues/13.

**Comment by gibiansky** [comment]
@sumitsahrawat Since this is ready to merge, go ahead and merge it.

**Comment by jdfreder** [comment]
:tada:

**Comment by sumitsahrawat** [comment]
Great, :+1: :rocket:. Thanks :bow:.

**Comment by jasongrout** [comment]
Great job!  Thanks for working on this!

**Comment by sumitsahrawat** [comment]
Thanks for the encouragement :+1:.

**Pull request merged**
