### PR TITLE
Added `ihaskell install` into build.sh

### PR DESCRIPTION
**Pull request by slon1024**

### CODE REVIEW

**Comment by gibiansky** [comment]
Good call. Will merge once travis verifies build.

**Comment by gibiansky** [comment]
Hmm, looks like this doesn't quite work. The issue is that `ihaskell install` requires `ipython >3.0`, but `./build.sh ihaskell` should be able to exit with 0 exit status regardless. 

Do you mind fixing this so that `./build.sh` does not fail if `ipython` is not present? For example, by returning a 0 exit code even if `ihaskell install` fails.

**Comment by gibiansky** [comment]
Ready to merge?

**Comment by slon1024** [comment]
Yeap :smile:

**Pull request merged**
