### PR TITLE
Allow using pre-installed ipython

### PR DESCRIPTION
**Pull request by sumitsahrawat**
Pinging @FranklinChen for comments.

### CODE REVIEW

**Comment by gibiansky** [comment]
@sumitsahrawat Is this for a hypothetical `Dockerfile` based on `ipython/ipython` or `jupyter/minimal` or something?

**Comment by sumitsahrawat** [comment]
I am in the process of editing the `Dockerfile` in `jupyter/docker-demo-images`. With this, installing IHaskell will be straightforward, just clone the repo, and execute `docker-common.sh`.

**Comment by gibiansky** [comment]
Then we'll have IHaskell on try.jupyter.org, I think. Awesome.

**Comment by gibiansky** [comment]
Would it be possible to merge this into one script that uses a conditional?

For example, check whether `ipython --version` returns 3.0 or above; if it doesn't, install it, and if it does, do nothing. 

That way, we can just use `ubuntu-install.sh` for Docker as well.

Something along these lines:
```bash
if [ `ipython --version | sed 's#\.# #g' | cut -f 1 -d ' '` -ge 3 ]; then
   # don't install ipython
else
  # install ipython
fi
```

**Comment by sumitsahrawat** [comment]
That looks like a better option, I'll update the PR.

**Comment by sumitsahrawat** [comment]
Another thing I noticed is that the docker containers use `ipython3` as opposed to `ipython`. Would IHaskell be able to work with that?

**Comment by gibiansky** [comment]
IHaskell should not care at all.

**Comment by FranklinChen** [comment]
Makes sense to check for IPython and not forcibly install it.

**Comment by gibiansky** [comment]
@sumitsahrawat Is this tested and ready-to-merge? (Note that I do not have Ubuntu on hand so cannot test this easily.)

**Comment by sumitsahrawat** [comment]
I'll squash these commits, I'm experimenting with this script in a virtual machine.

**Comment by sumitsahrawat** [comment]
This works. Tested with and without pre-installed ipython. Also tested with a lower version of ipython (v2.0) pre-installed.

**Comment by gibiansky** [comment]
Great. Will merge shortly.

**Pull request merged**
