### PR TITLE
Add `buffers` field of the Wire Protocol

### LINKED ISSUE #1144: MessageHeader buffers
There is a way for the Jupyter frontend to communicate arbitrary binary blobs with the kernel, by the [`IMessage.buffers`](https://github.com/jupyterlab/jupyterlab/blob/b66bb79116285ccbd0876a6263ac2c0d6de27c33/packages/services/src/kernel/messages.ts#L277)

It would be nice if the IHaskell IPython kernel could send and receive `buffers`. I suppose they would be added here, in the [`IHaskell.IPython.Types.MessageHeader`](https://github.com/gibiansky/IHaskell/blob/9dd237ea0480302fd7a34c0eeef0fe97bca3ae1a/ipython-kernel/src/IHaskell/IPython/Types.hs#L149). 

 This new field would have the type `buffers :: [ByteString]`, just like `mhIdentifiers :: [ByteString]` which, by the way, stores the ASCII-encoded `mhSessionId` and `mhMessageId`.

Perhaps `buffers` was added in some latter Jupyter protocol version which IHaskell hasn't caught up with? I haven't investigated yet.

### PR DESCRIPTION
**Pull request by jamesdbrock**
Resolves #1144

### CODE REVIEW

**Comment by vaibhavsagar** [comment]
Thanks!

**Comment by vaibhavsagar** [comment]
Out of curiousity: why `parsec` instead of `attoparsec`?

**Comment by jamesdbrock** [comment]
@vaibhavsagar Because the type of the "input stream" that we're parsing here is `[ByteString]`, where the individual tokens are of type `ByteString`. Parsec and Megaparsec can parse weird input streams like that, but Attoparsec can only parse two types of input streams: `Text` and `ByteString`. And Parsec is already a [dependency of IHaskell](https://github.com/gibiansky/IHaskell/blob/f540feb155353427427e883462de44b0c100d64e/ihaskell.cabal#L76), but Megaparsec isn't, so I figured adding Parsec as a dependency of ipython-kernel was the least-dependency-adding thing to do.

Thanks as always for quick merging!

**Comment by vaibhavsagar** [comment]
That makes sense, thanks for the clarification and the PR!

**Pull request merged**
