### PR TITLE
Upgrade travis to container based builds

### PR DESCRIPTION
**Pull request by sumitsahrawat**
This should solve some issues regarding out of memory conditions.

### CODE REVIEW

**Comment by sumitsahrawat** [comment]
@gibiansky This will not work until https://github.com/travis-ci/apt-source-whitelist/pull/150 is merged.

**Comment by gibiansky** [comment]
This is going to be great when it merges...

**Comment by gibiansky** [comment]
Frustrating that it is taking so long to merge. Looks like there are merge conflicts now...

**Comment by sumitsahrawat** [comment]
I don't know why I didn't realize this before. It can be done without using `sudo` at all :)

This is meaningless now.

**Comment by gibiansky** [comment]
I am also working on a new travis based build using Travis' new container CI

**Pull request closed without merging**
