### PR TITLE
-Wall the things

### PR DESCRIPTION
**Pull request by erikd**
Well at least in IHaskell itself. Will do the ``ihashell-display` packages in a separate PR.

### CODE REVIEW

**Comment by vaibhavsagar** [comment]
This is amazing, thanks! There's a test failure on GHC 8.0, will happily merge once that is resolved.

**Comment by vaibhavsagar** [comment]
I'm also seeing a couple of warnings because of `-Wname-shadowing` when I try to build this locally, are you planning to fix these? I don't have strong feelings about this one either way, but if you aren't it might be worth turning this one off in the `.cabal` file?

**Comment by erikd** [comment]
This time for sure!

**Comment by gibiansky** [comment]
<3 to this and getting rid of GHC pre-8.0 shit/ifdefs

**Pull request merged**
