### PR TITLE
stack resolver lts-14.6, GHC 8.6.5

### PR DESCRIPTION
**Pull request by jamesdbrock**
Add dependencies to Test-Suite to make it pass

### CODE REVIEW

**Comment by vaibhavsagar** [comment]
This won't work until you update the HLint code to use the new API, see https://github.com/gibiansky/IHaskell/issues/1066.

**Comment by jamesdbrock** [comment]
It seems to Work On My Machine and on my branch in Travis.

The test which failed here failed with

```
[NbConvertApp] ERROR | Kernel died while waiting for execute reply.
```

Is that an HLint problem?

**Comment by jamesdbrock** [comment]
I would like to rerun that build job, how do I do that in Travis anyway...

**Comment by jamesdbrock** [comment]
Oh I forgot, here's the link to sucessful Travis build of the same commit.

https://travis-ci.org/jamesdbrock/IHaskell/builds/586329058

**Comment by jamesdbrock** [comment]
Oh I don't have the <kbd>Restart Build</kbd> button because I don't own the repository. Unless you're sure this in an HLint problem and the build will fail, would you please try the build again @vaibhavsagar ?

**Comment by jamesdbrock** [comment]
Ok build restarted.

**Comment by jamesdbrock** [comment]
Hey it built on the third try. Thoughts? I tried using HLint in a notebook with this build and it seems fine.

**Comment by jamesdbrock** [comment]
Reference: http://hackage.haskell.org/package/hlint-2.2.2/changelog

**Comment by vaibhavsagar** [comment]
I also don't like that we're depending on the IHaskell display packages in the test suite, because those packages in turn depend on IHaskell, so there is a cyclic dependency if you need to run the tests for the package build (as Nix does).

**Comment by jamesdbrock** [comment]
Oh. Ok I'll try again without those dependencies.

**Comment by jamesdbrock** [comment]
So without those dependencies for `Test-Suite hspec` I get a series of errors `stack test` that looks like:

```
ihaskell            >   src/tests/IHaskell/Test/Eval.hs:104:5: 
ihaskell            >   1) Code Evaluation evaluates expressions
ihaskell            >        uncaught exception: SourceError
ihaskell            >        Could not load module ‘IHaskell.Display.Blaze’
ihaskell            >        It is a member of the hidden package ‘ihaskell-blaze-0.3.0.1’.
ihaskell            >        You can run ‘:set -package ihaskell-blaze’ to expose it.
ihaskell            >        (Note: this unloads all the modules in the current scope.)
ihaskell            >        Use -v to see a list of the files searched for.
ihaskell            >        Could not load module ‘IHaskell.Display.Aeson’
ihaskell            >        It is a member of the hidden package ‘ihaskell-aeson-0.3.0.1’.
ihaskell            >        You can run ‘:set -package ihaskell-aeson’ to expose it.
ihaskell            >        (Note: this unloads all the modules in the current scope.)
ihaskell            >        Use -v to see a list of the files searched for.
```
I'll investigate later.

**Comment by vaibhavsagar** [comment]
Yeah, this is an issue with Stack >=2. I think it's frustrating that we don't have control over this aspect of the tests, when it worked previously.

**Comment by vaibhavsagar** [comment]
This is what I get with `hlint-2.2.2`:

```
[21 of 25] Compiling IHaskell.Eval.Lint ( src/IHaskell/Eval/Lint.hs, dist/build/IHaskell/Eval/Lint.o )

src/IHaskell/Eval/Lint.hs:59:41: error:
    • Couldn't match type ‘(ExtsModule, [a0])’ with ‘ModuleEx’
      Expected type: [ModuleEx]
        Actual type: [(ExtsModule, [a0])]
    • In the third argument of ‘applyHints’, namely
        ‘(map (\ m -> (m, [])) modules)’
      In the expression:
        applyHints classify hint (map (\ m -> (m, [])) modules)
      In an equation for ‘ideas’:
          ideas = applyHints classify hint (map (\ m -> (m, [])) modules)
   |
59 |       ideas = applyHints classify hint (map (\m -> (m, [])) modules)
   |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by vaibhavsagar** [comment]
I've fixed the HLint issue in #1095.

**Comment by vaibhavsagar** [comment]
Superseded by #1096.

**Pull request closed without merging**
