### PR TITLE
Ihaskell gnuplot

### PR DESCRIPTION
**Pull request by kfiz**
Display instance for (haskell-)gnuplot.

### CODE REVIEW

**Comment by gibiansky** [comment]
LGTM. will merge this manually

**Comment by gibiansky** [comment]
Working on this now. Probably need to bump to LTS-5.5 to support this plus all of other IHaskell addons.

**Comment by gibiansky** [comment]
@kfiz I've cleaned up this branch and gotten it to build on the `kfiz-ihaskell-gnuplot` branch.

Can you give an example of the code that should produce a plot? I can't understand the `gnuplot` documentation (or complete lack thereof) enough to figure out how to get a plot going (other than `plotList` and `plotFunc` and the `.Simple` family of functions...)

**Comment by kfiz** [comment]
I've sent you a jupyter notebook via email with some demo plots. Hope this works. If it doesn't I can send you the demo file that is shipped with haskell gnuplot and you can run the examples, that are given there. All of them worked for me in IHaskell.

**Comment by gibiansky** [comment]
Finally merged! Thanks!

**Pull request closed without merging**
