### PR TITLE
Handle plugin initialization using :set -fplugin module

### PR DESCRIPTION
**Pull request by abarbu**
This addresses #1289

Previously plugins were (almost) silently ignored. I also got rid of a misleading comment.

Plugins work as expected now.

### CODE REVIEW

**Review by vaibhavsagar — APPROVED** [review]
Approved contingent on tests passing!

**Comment by vaibhavsagar** [comment]
IIRC you still have commit privileges so you could merge this yourself but I'm hoping you will fix the compilation failures on GHC <8.10 first :smile:. I would be fine with a solution that compiles but doesn't provide plugin loading functionality on older GHCs we support, I know getting everything working across multiple versions can be a huge pain.

**Comment by vaibhavsagar** [comment]
This looks great, can you fix the test failure by changing the expected output to the new output?

**Comment by abarbu** [comment]
Thanks! I incorporated those changes. Looks like everything should pass now.
I don't think I have commit access anymore, if you don't mind merging.

**Comment by vaibhavsagar** [comment]
Thanks so much!

**Pull request merged**
