### PR TITLE
Adding new widgets

### PR DESCRIPTION
**Pull request by sumitsahrawat**
+ Valid: A widget to display boolean values.
+ Proxy: A widget that contains at most one DOMWidget in it.
+ PlaceProxy: A Proxy widget with a selector (string) value.

Will have to investigate how the selector is used by PlaceProxy.

### CODE REVIEW

**Comment by sumitsahrawat** [comment]
Note to self: The example notebooks will also need to be updated.

**Comment by gibiansky** [comment]
Is the only thing remaining that is blocking https://github.com/jupyter/docker-demo-images/pull/71#issuecomment-139978343 making a release? If so, I can create a release and get it on Hackage / Stackage today(ish).

**Comment by sumitsahrawat** [comment]
Yup, a release will set everything right. Currently the examples are not part of the `extra-source-files`, so we can make a release as it is.

I will work on the examples, and then we can have another release including new examples.

**Comment by rgbkrk** [comment]
Yep, that's the only blocker.

**Comment by gibiansky** [comment]
Updated versions on hackage should be available. `0.8.0.0`, `0.8.1.0`, `0.2.0.0` for `ihaskell` `ipython-kernel`, and `ihaskell-widgets`, respectively.

**Pull request merged**
